name: Run PR Checks
on:
  pull_request:
    branches:
      - main
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Use pnpm 🅿️
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node 20 ✨
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile
      - name: Format OK 🖌️
        run: pnpm fmt:check
      - name: Lint OK 🧹
        run: pnpm lint
      - name: Test OK 🧪
        run: pnpm test
      - name: Build OK 🔨
        run: pnpm build
